"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "hi" | "gu";

interface Translations {
    [key: string]: {
        [key: string]: string;
    };
}

const translations: Translations = {
    en: {
        dashboard: "Dashboard",
        myFamily: "My Family",
        addMember: "Add Member",
        search: "Search",
        adminPanel: "Admin Panel",
        totalFamilies: "Total Families",
        totalMembers: "Total Members",
        aliveMembers: "Alive Members",
        deceasedMembers: "Deceased Members",
        recentActivity: "Recent Activity",
        demographics: "Demographics (Gender)",
        logout: "Logout",
        language: "Language",
        english: "English",
        hindi: "Hindi",
        gujarati: "Gujarati",
        viewDetails: "View Details",
        familyHeader: "{name}'s Family",
        searchDirectory: "Search Directory",
        filterByCity: "Filter by City",
        filterByVillage: "Filter by Village/Town",
        filterByState: "Filter by State",
        filterByCaste: "Filter by Caste/Community",
        searching: "Searching...",
        noResults: "No families found matching your search criteria.",
        hideMembers: "Hide Members",
        showMembers: "Show Members",
        self: "Self",
        welcome: "Welcome",
        familiesOverview: "My Families Overview",
        registerNewFamily: "Register New Family",
        primaryInfo: "Primary Information",
        fullNamePlaceholder: "Full Name",
        selectGender: "Select Gender",
        male: "Male",
        female: "Female",
        other: "Other",
        optional: "Optional",
        familyIdOptional: "Family ID (Optional)",
        fatherNameOptional: "Father's Name (Optional)",
        motherNameOptional: "Mother's Name (Optional)",
        castePlaceholder: "E.g., Rajput, Brahmin, etc.",
        contactNumberPlaceholder: "Primary Phone Number",
        familyPhotoOptional: "Family Photo (Optional)",
        addressDetails: "Address Details",
        streetAddress: "Street Address",
        streetPlaceholder: "House No, Street, Landmark",
        villageTown: "Village / Town",
        villagePlaceholder: "Village Name",
        selectState: "Select State",
        selectCity: "Select City",
        enterCityName: "Enter City Name",
        selectStateFirst: "Select State First",
        addFamilyMember: "Add Family Member",
        maritalStatus: "Marital Status",
        single: "Single",
        married: "Married",
        divorced: "Divorced",
        widowed: "Widowed",
        bloodGroup: "Blood Group",
        education: "Education",
        occupation: "Occupation",
        memberIsAlive: "Member is Alive",
        addingMember: "Adding Member...",
        addMemberToFamily: "Add Member to Family",
        relationPlaceholder: "e.g., Self, Wife, Son",
        spouseNamePlaceholder: "Full Name of Spouse",
        editFamilyMember: "Edit Family Member",
        updating: "Updating...",
        updateMemberDetails: "Update Member Details",
        loadingMemberData: "Loading member data...",
        familyDetails: "Family Details",
        confirmDeleteMember: "Are you sure you want to delete this member?",
        headOfFamilyLabel: "Head of Family",
        auto: "Auto",
        loadingFamDetails: "Loading family details...",
        years_short: "y",
        months_short: "m",
        editMember: "Edit Member",
        deleteMember: "Delete Member",
        editHead: "Edit Head of Family",
        registering: "Registering...",
        registerFamily: "Register Another Family",
        familyId: "Family ID",
        caste: "Caste",
        dob: "Date of Birth",
        age: "Age",
        fatherName: "Father's Name",
        motherName: "Mother's Name",
        contact: "Contact",
        address: "Address",
        membersDirectory: "Members Directory",
        photo: "Photo",
        name: "Name",
        relation: "Relation",
        spouseName: "Spouse Name",
        gender: "Gender",
        status: "Status",
        alive: "Alive",
        deceased: "Deceased",
        headOfFamily: "Head of Family",
        total: "Total",
        edit: "Edit",
        delete: "Delete",
        actions: "Actions",
        save: "Save",
        cancel: "Cancel",
        loading: "Loading...",
        confirmDelete: "Are you sure you want to delete this?",
        searchPlaceholder: "Search by Family Head or ID...",
        district: "District",
        state: "State",
        pincode: "Pincode",
        downloadPDF: "Download PDF",
        community: "Community",
        relationships: "Relationships",
        contactAndAddress: "Contact & Address"
    },
    hi: {
        dashboard: "डैशबोर्ड",
        myFamily: "मेरा परिवार",
        addMember: "सदस्य जोड़ें",
        search: "खोजें",
        adminPanel: "प्रशासनिक पैनल",
        totalFamilies: "कुल परिवार",
        totalMembers: "कुल सदस्य",
        aliveMembers: "जीवित सदस्य",
        deceasedMembers: "मृत सदस्य",
        recentActivity: "हाल की गतिविधि",
        demographics: "जनसांख्यिकी (लिंग)",
        logout: "लॉगआउट",
        language: "भाषा",
        english: "अंग्रेजी",
        hindi: "हिंदी",
        gujarati: "गुजराती",
        viewDetails: "विवरण देखें",
        familyHeader: "{name} का परिवार",
        searchDirectory: "खोज निर्देशिका",
        filterByCity: "शहर द्वारा फ़िल्टर करें",
        filterByVillage: "गांव/शहर द्वारा फ़िल्टर करें",
        filterByState: "राज्य द्वारा फ़िल्टर करें",
        filterByCaste: "जाति/समुदाय द्वारा फ़िल्टर करें",
        searching: "खोज रहे हैं...",
        noResults: "आपके खोज मापदंड से मेल खाने वाला कोई परिवार नहीं मिला।",
        hideMembers: "सदस्य छिपाएं",
        showMembers: "सदस्य दिखाएं",
        self: "स्वयं",
        welcome: "स्वागत है",
        familiesOverview: "मेरे परिवारों का विवरण",
        registerNewFamily: "नया परिवार पंजीकृत करें",
        primaryInfo: "प्राथमिक जानकारी",
        fullNamePlaceholder: "पूरा नाम",
        selectGender: "लिंग चुनें",
        male: "पुरुष",
        female: "महिला",
        other: "अन्य",
        optional: "वैकल्पिक",
        familyIdOptional: "परिवार आईडी (वैकल्पिक)",
        fatherNameOptional: "पिता का नाम (वैकल्पिक)",
        motherNameOptional: "माता का नाम (वैकल्पिक)",
        castePlaceholder: "जैसे: राजपूत, ब्राह्मण, आदि",
        contactNumberPlaceholder: "प्राथमिक फोन नंबर",
        familyPhotoOptional: "पारिवारिक फोटो (वैकल्पिक)",
        addressDetails: "पते का विवरण",
        streetAddress: "गली का पता",
        streetPlaceholder: "मकान नंबर, गली, लैंडमार्क",
        villageTown: "गांव / शहर",
        villagePlaceholder: "गांव का नाम",
        selectState: "राज्य चुनें",
        selectCity: "शहर चुनें",
        enterCityName: "शहर का नाम दर्ज करें",
        selectStateFirst: "पहले राज्य चुनें",
        addFamilyMember: "परिवार का सदस्य जोड़ें",
        maritalStatus: "वैवाहिक स्थिति",
        single: "अविवाहित",
        married: "विवाहित",
        divorced: "तलाकशुदा",
        widowed: "विधवा/विधुर",
        bloodGroup: "रक्त समूह",
        education: "शिक्षा",
        occupation: "व्यवसाय",
        memberIsAlive: "सदस्य जीवित है",
        addingMember: "सदस्य जोड़ा जा रहा है...",
        addMemberToFamily: "परिवार में सदस्य जोड़ें",
        relationPlaceholder: "जैसे: स्वयं, पत्नी, पुत्र",
        spouseNamePlaceholder: "जीवनसाथी का पूरा नाम",
        editFamilyMember: "परिवार के सदस्य को संपादित करें",
        updating: "अपडेट हो रहा है...",
        updateMemberDetails: "सदस्य विवरण अपडेट करें",
        loadingMemberData: "सदस्य डेटा लोड हो रहा है...",
        familyDetails: "परिवार का विवरण",
        confirmDeleteMember: "क्या आप वाकई इस सदस्य को हटाना चाहते हैं?",
        headOfFamilyLabel: "परिवार का मुखिया",
        auto: "ऑટો",
        loadingFamDetails: "परिवार का विवरण लोड हो रहा है...",
        years_short: "वर्ष",
        months_short: "महीने",
        editMember: "सदस्य को संपादित करें",
        deleteMember: "सदस्य को हटाएं",
        editHead: "परिवार के मुखिया को संपादित करें",
        registering: "पंजीकरण हो रहा है...",
        registerFamily: "नया परिवार पंजीकृत करें",
        familyId: "परिवार आईडी",
        caste: "जाति",
        dob: "जन्म तिथि",
        age: "आयु",
        fatherName: "पिता का नाम",
        motherName: "माता का नाम",
        contact: "संपर्क",
        address: "पता",
        membersDirectory: "सदस्य निर्देशिका",
        photo: "फोटो",
        name: "नाम",
        relation: "संबंध",
        spouseName: "पति/पत्नी का नाम",
        gender: "लिंग",
        status: "स्थिति",
        alive: "जीवित",
        deceased: "मृत",
        headOfFamily: "परिवार का मुखिया",
        total: "कुल",
        edit: "संपादित करें",
        delete: "हटाएं",
        actions: "कार्य",
        save: "सहेजें",
        cancel: "रद्द करें",
        loading: "लोड हो रहा है...",
        confirmDelete: "क्या आप वाकई इसे हटाना चाहते हैं?",
        searchPlaceholder: "परिवार के मुखिया या आईडी द्वारा खोजें...",
        district: "ज़िला",
        state: "राज्य",
        pincode: "पिन कोड",
        downloadPDF: "पीडीएफ डाउनलोड करें",
        community: "समुदाय",
        relationships: "संबंध",
        contactAndAddress: "संपर्क और पता"
    },
    gu: {
        dashboard: "ડેશબોર્ડ",
        myFamily: "મારો પરિવાર",
        addMember: "સભ્ય ઉમેરો",
        search: "શોધ",
        adminPanel: "એડમિન પેનલ",
        totalFamilies: "કુલ પરિવારો",
        totalMembers: "કુલ સભ્યો",
        aliveMembers: "જીવંત સભ્યો",
        deceasedMembers: "મૃત સભ્યો",
        recentActivity: "તાજેતરની પ્રવૃત્તિ",
        demographics: "વસ્તી વિષયક (જાતિ)",
        logout: "લોગઆઉટ",
        language: "ભાષા",
        english: "અંગ્રેજી",
        hindi: "હિન્દી",
        gujarati: "ગુજરાતી",
        viewDetails: "વિગતો જુઓ",
        familyHeader: "{name} નો પરિવાર",
        searchDirectory: "શોધ નિર્દેશિકા",
        filterByCity: "શહેર દ્વારા ફિલ્ટર કરો",
        filterByVillage: "ગામ/શહેર દ્વારા ફિલ્ટર કરો",
        filterByState: "રાજ્ય દ્વારા ફિલ્ટર કરો",
        filterByCaste: "જ્ઞાતિ/સમુદાય દ્વારા ફિલ્ટર કરો",
        searching: "શોધ કરી રહ્યા છીએ...",
        noResults: "તમારા શોધ માપદંડ સાથે મેળ ખાતા કોઈ પરિવારો મળ્યા નથી.",
        hideMembers: "સભ્યો છુપાવો",
        showMembers: "સભ્યો બતાવો",
        self: "પોતે",
        welcome: "સ્વાગત છે",
        familiesOverview: "મારા પરિવારોની વિગત",
        registerNewFamily: "નવો પરિવાર નોંધો",
        primaryInfo: "પ્રાથમિક માહિતી",
        fullNamePlaceholder: "પૂરું નામ",
        selectGender: "લિંગ પસંદ કરો",
        male: "પુરુષ",
        female: "સ્ત્રી",
        other: "અન્ય",
        optional: "વૈકલ્પિક",
        familyIdOptional: "પરિવાર આઈડી (વૈકલ્પિક)",
        fatherNameOptional: "પિતાનું નામ (વૈકલ્પિક)",
        motherNameOptional: "માતાનું નામ (વૈકલ્પિક)",
        castePlaceholder: "દા.ત., રાજપૂત, બ્રાહ્મણ, વગેરે",
        contactNumberPlaceholder: "પ્રાથમિક ફોન નંબર",
        familyPhotoOptional: "પરિવારનો ફોટો (વૈકલ્પિક)",
        addressDetails: "સરનામાંની વિગતો",
        streetAddress: "શેરીનું સરનામું",
        streetPlaceholder: "મકાન નંબર, શેરી, લેન્ડમાર્ક",
        villageTown: "ગામ / શહેર",
        villagePlaceholder: "ગામનું નામ",
        selectState: "રાજ્ય પસંદ કરો",
        selectCity: "શહેર પસંદ કરો",
        enterCityName: "શહેરનું નામ લખો",
        selectStateFirst: "પહેલા રાજ્ય પસંદ કરો",
        addFamilyMember: "પરિવારનો સભ્ય ઉમેરો",
        maritalStatus: "વૈવાહિક સ્થિતિ",
        single: "અપરિણીત",
        married: "પરિણીત",
        divorced: "છૂટાછેડા લીધેલ",
        widowed: "વિધવા/વિધુર",
        bloodGroup: "બ્લડ ગ્રુપ",
        education: "શિક્ષણ",
        occupation: "વ્યવસાય",
        memberIsAlive: "સભ્ય જીવિત છે",
        addingMember: "સભ્ય ઉમેરાઈ રહ્યો છે...",
        addMemberToFamily: "પરિવારમાં સભ્ય ઉમેરો",
        relationPlaceholder: "દા.ત., પોતે, પત્ની, પુત્ર",
        spouseNamePlaceholder: "જીવનસાથીનું પૂરું નામ",
        editFamilyMember: "પરિવારના સભ્યની વિગતો સુધારો",
        updating: "સુધારો થઈ રહ્યો છે...",
        updateMemberDetails: "સભ્યની વિગતો અપડેટ કરો",
        loadingMemberData: "સભ્યની વિગતો લોડ થઈ રહી છે...",
        familyDetails: "પરિવારની વિગત",
        confirmDeleteMember: "શું તમે ખરેખર આ સભ્યને કાઢી નાખવા માંગો છો?",
        headOfFamilyLabel: "પરિવારના વડા",
        auto: "ઓટો",
        loadingFamDetails: "પરિવારની વિગતો લોડ થઈ રહી છે...",
        years_short: "વષ",
        months_short: "મહિના",
        editMember: "સભ્યની વિગતો સુધારો",
        deleteMember: "સભ્યને કાઢી નાખો",
        editHead: "પરિવારના વડાની વિગતો સુધારો",
        registering: "નોંધણી થઈ રહી છે...",
        registerFamily: "બીજો પરિવાર નોંધો",
        familyId: "પરિવાર આઈડી",
        caste: "જ્ઞાતિ",
        dob: "જન્મ તારીખ",
        age: "ઉંમર",
        fatherName: "પિતાનું નામ",
        motherName: "માતાનું નામ",
        contact: "સંપર્ક",
        address: "સરનામું",
        membersDirectory: "સભ્યોની ડિરેક્ટરી",
        photo: "ફોટો",
        name: "નામ",
        relation: "સંબંધ",
        spouseName: "પતિ/પત્નીનું નામ",
        gender: "જાતિ",
        status: "સ્થિતિ",
        alive: "જીવંત",
        deceased: "અવસાન",
        headOfFamily: "પરિવારના વડા",
        total: "કુલ",
        edit: "ફેરફાર કરો",
        delete: "ડીલીટ",
        actions: "ક્રિયાઓ",
        save: "સાચવો",
        cancel: "રદ કરો",
        loading: "લોડ થઈ રહ્યું છે...",
        confirmDelete: "શું તમે ખરેખર આ કાઢી નાખવા માંગો છો?",
        searchPlaceholder: "પરિવારના વડા અથવા આઈડી દ્વારા શોધો...",
        district: "જિલ્લો",
        state: "રાજ્ય",
        pincode: "પિન કોડ",
        downloadPDF: "પીડીએફ ડાઉનલોડ કરો",
        community: "સમુદાય",
        relationships: "સંબંધો",
        contactAndAddress: "સંપર્ક અને સરનામું"
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>("en");

    useEffect(() => {
        const savedLang = localStorage.getItem("language") as Language;
        if (savedLang && translations[savedLang]) {
            setLanguageState(savedLang);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("language", lang);
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
};
